import { BatchRosterItemSchema, type BatchRosterItem } from "@vip/core-model";

/**
 * Batch 001 sports — 25 deliberately messy Dealer Inventory cards.
 * $5–$50 rookies / parallels / numbered / autos / relics. Not 25 base commons.
 * Filenames are PaperStream-shaped so the Ricoh drop can reuse them.
 */
const RAW: BatchRosterItem[] = [
  {
    slot: 1,
    category: "sports",
    fileStem: "2023_prizm_victor_wembanyama_136_silver_front",
    expected: {
      year: 2023,
      brand: "Prizm",
      player: "Victor Wembanyama",
      collectorNumber: "136",
      parallel: "Silver",
      serialMax: null,
      autograph: false,
      relic: false,
      displayName: "2023 Prizm Victor Wembanyama #136 Silver",
    },
    intendedAskBandUsd: { low: 15, high: 40 },
    messFlags: ["parallel", "fixture-catalog-may-drop-parallel"],
  },
  {
    slot: 2,
    category: "sports",
    fileStem: "2020_prizm_joe_burrow_307_pink_ice_front",
    expected: {
      year: 2020,
      brand: "Prizm",
      player: "Joe Burrow",
      collectorNumber: "307",
      parallel: "Pink Ice",
      serialMax: null,
      autograph: false,
      relic: false,
      displayName: "2020 Prizm Joe Burrow #307 Pink Ice",
    },
    intendedAskBandUsd: { low: 12, high: 35 },
    messFlags: ["rookie", "parallel"],
  },
  {
    slot: 3,
    category: "sports",
    fileStem: "2018_prizm_luka_doncic_280_red_white_blue_front",
    expected: {
      year: 2018,
      brand: "Prizm",
      player: "Luka Doncic",
      collectorNumber: "280",
      parallel: "Red White Blue",
      serialMax: null,
      autograph: false,
      relic: false,
      displayName: "2018 Prizm Luka Doncic #280 Red White Blue",
    },
    intendedAskBandUsd: { low: 20, high: 50 },
    messFlags: ["rookie", "parallel"],
  },
  {
    slot: 4,
    category: "sports",
    fileStem: "2023_select_cj_stroud_43_tie_dye_numbered_25_front",
    expected: {
      year: 2023,
      brand: "Select",
      player: "C.J. Stroud",
      collectorNumber: "43",
      parallel: "Tie-Dye",
      serialMax: 25,
      autograph: false,
      relic: false,
      displayName: "2023 Select C.J. Stroud #43 Tie-Dye /25",
    },
    intendedAskBandUsd: { low: 18, high: 45 },
    messFlags: ["numbered", "parallel", "brand-vs-prizm-token"],
  },
  {
    slot: 5,
    category: "sports",
    fileStem: "2022_mosaic_paolo_banchero_231_genesis_front",
    expected: {
      year: 2022,
      brand: "Mosaic",
      player: "Paolo Banchero",
      collectorNumber: "231",
      parallel: "Genesis",
      serialMax: null,
      autograph: false,
      relic: false,
      displayName: "2022 Mosaic Paolo Banchero #231 Genesis",
    },
    intendedAskBandUsd: { low: 15, high: 40 },
    messFlags: ["rare-parallel", "rookie"],
  },
  {
    slot: 6,
    category: "sports",
    fileStem: "2019_optic_zion_williamson_158_rated_rookie_holo_front",
    expected: {
      year: 2019,
      brand: "Optic",
      player: "Zion Williamson",
      collectorNumber: "158",
      parallel: null,
      serialMax: null,
      autograph: false,
      relic: false,
      displayName: "2019 Optic Zion Williamson #158 Rated Rookie Holo",
    },
    intendedAskBandUsd: { low: 10, high: 28 },
    messFlags: ["rookie", "holo", "product-line"],
  },
  {
    slot: 7,
    category: "sports",
    fileStem: "2020_mosaic_justin_herbert_204_pink_camo_front",
    expected: {
      year: 2020,
      brand: "Mosaic",
      player: "Justin Herbert",
      collectorNumber: "204",
      parallel: "Pink Camo",
      serialMax: null,
      autograph: false,
      relic: false,
      displayName: "2020 Mosaic Justin Herbert #204 Pink Camo",
    },
    intendedAskBandUsd: { low: 10, high: 30 },
    messFlags: ["rookie", "parallel"],
  },
  {
    slot: 8,
    category: "sports",
    fileStem: "2023_bowman_chrome_jackson_holliday_bcp20_auto_front",
    expected: {
      year: 2023,
      brand: "Bowman",
      player: "Jackson Holliday",
      collectorNumber: "bcp20",
      parallel: null,
      serialMax: null,
      autograph: true,
      relic: false,
      displayName: "2023 Bowman Chrome Jackson Holliday BCP-20 Auto",
    },
    intendedAskBandUsd: { low: 20, high: 50 },
    messFlags: ["auto", "chrome", "alpha-number"],
  },
  {
    slot: 9,
    category: "sports",
    fileStem: "2021_prizm_ja_morant_120_green_shimmer_front",
    expected: {
      year: 2021,
      brand: "Prizm",
      player: "Ja Morant",
      collectorNumber: "120",
      parallel: "Green Shimmer",
      serialMax: null,
      autograph: false,
      relic: false,
      displayName: "2021 Prizm Ja Morant #120 Green Shimmer",
    },
    intendedAskBandUsd: { low: 12, high: 32 },
    messFlags: ["parallel"],
  },
  {
    slot: 10,
    category: "sports",
    fileStem: "2018_select_saquon_barkley_17_tie_dye_front",
    expected: {
      year: 2018,
      brand: "Select",
      player: "Saquon Barkley",
      collectorNumber: "17",
      parallel: "Tie-Dye",
      serialMax: null,
      autograph: false,
      relic: false,
      displayName: "2018 Select Saquon Barkley #17 Tie-Dye",
    },
    intendedAskBandUsd: { low: 8, high: 22 },
    messFlags: ["parallel", "brand-vs-prizm-token"],
  },
  {
    slot: 11,
    category: "sports",
    fileStem: "2022_prizm_kenny_pickett_301_orange_disco_front",
    expected: {
      year: 2022,
      brand: "Prizm",
      player: "Kenny Pickett",
      collectorNumber: "301",
      parallel: "Orange Disco",
      serialMax: null,
      autograph: false,
      relic: false,
      displayName: "2022 Prizm Kenny Pickett #301 Orange Disco",
    },
    intendedAskBandUsd: { low: 5, high: 15 },
    messFlags: ["rookie", "parallel"],
  },
  {
    slot: 12,
    category: "sports",
    fileStem: "2020_prizm_justin_jefferson_398_green_scope_numbered_75_front",
    expected: {
      year: 2020,
      brand: "Prizm",
      player: "Justin Jefferson",
      collectorNumber: "398",
      parallel: "Green Scope",
      serialMax: 75,
      autograph: false,
      relic: false,
      displayName: "2020 Prizm Justin Jefferson #398 Green Scope /75",
    },
    intendedAskBandUsd: { low: 18, high: 45 },
    messFlags: ["numbered", "parallel", "rookie"],
  },
  {
    slot: 13,
    category: "sports",
    fileStem: "2019_prizm_kyler_murray_152_pink_ice_front",
    expected: {
      year: 2019,
      brand: "Prizm",
      player: "Kyler Murray",
      collectorNumber: "152",
      parallel: "Pink Ice",
      serialMax: null,
      autograph: false,
      relic: false,
      displayName: "2019 Prizm Kyler Murray #152 Pink Ice",
    },
    intendedAskBandUsd: { low: 8, high: 20 },
    messFlags: ["rookie", "parallel"],
  },
  {
    slot: 14,
    category: "sports",
    fileStem: "2024_topps_chrome_paul_skenes_89_auto_relic_front",
    expected: {
      year: 2024,
      brand: "Topps Chrome",
      player: "Paul Skenes",
      collectorNumber: "89",
      parallel: null,
      serialMax: null,
      autograph: true,
      relic: true,
      displayName: "2024 Topps Chrome Paul Skenes #89 Auto Relic",
    },
    intendedAskBandUsd: { low: 25, high: 50 },
    messFlags: ["auto", "relic", "chrome"],
  },
  {
    slot: 15,
    category: "sports",
    fileStem: "2023_prizm_brandon_miller_140_choice_tiger_stripe_front",
    expected: {
      year: 2023,
      brand: "Prizm",
      player: "Brandon Miller",
      collectorNumber: "140",
      parallel: "Tiger Stripe",
      serialMax: null,
      autograph: false,
      relic: false,
      displayName: "2023 Prizm Brandon Miller #140 Choice Tiger Stripe",
    },
    intendedAskBandUsd: { low: 12, high: 35 },
    messFlags: ["choice-product", "parallel", "rookie"],
  },
  {
    slot: 16,
    category: "sports",
    fileStem: "2021_select_mac_jones_51_die_cut_front",
    expected: {
      year: 2021,
      brand: "Select",
      player: "Mac Jones",
      collectorNumber: "51",
      parallel: "Die-Cut",
      serialMax: null,
      autograph: false,
      relic: false,
      displayName: "2021 Select Mac Jones #51 Die-Cut",
    },
    intendedAskBandUsd: { low: 5, high: 14 },
    messFlags: ["die-cut", "rookie"],
  },
  {
    slot: 17,
    category: "sports",
    fileStem: "2022_optic_aj_brown_downtown_front",
    expected: {
      year: 2022,
      brand: "Optic",
      player: "A.J. Brown",
      collectorNumber: null,
      parallel: "Downtown",
      serialMax: null,
      autograph: false,
      relic: false,
      displayName: "2022 Donruss Optic A.J. Brown Downtown",
    },
    intendedAskBandUsd: { low: 20, high: 50 },
    messFlags: ["insert-not-base", "no-card-number"],
  },
  {
    slot: 18,
    category: "sports",
    fileStem: "2020_contenders_joe_burrow_104_rookie_ticket_auto_front",
    expected: {
      year: 2020,
      brand: "Panini",
      player: "Joe Burrow",
      collectorNumber: "104",
      parallel: null,
      serialMax: null,
      autograph: true,
      relic: false,
      displayName: "2020 Contenders Joe Burrow #104 Rookie Ticket Auto",
    },
    intendedAskBandUsd: { low: 20, high: 50 },
    messFlags: ["auto", "product-line-unmapped-brand"],
  },
  {
    slot: 19,
    category: "sports",
    fileStem: "2018_prizm_trae_young_78_pink_ice_front",
    expected: {
      year: 2018,
      brand: "Prizm",
      player: "Trae Young",
      collectorNumber: "78",
      parallel: "Pink Ice",
      serialMax: null,
      autograph: false,
      relic: false,
      displayName: "2018 Prizm Trae Young #78 Pink Ice",
    },
    intendedAskBandUsd: { low: 10, high: 28 },
    messFlags: ["rookie", "parallel"],
  },
  {
    slot: 20,
    category: "sports",
    fileStem: "2023_select_anthony_richardson_47_club_level_gold_numbered_10_front",
    expected: {
      year: 2023,
      brand: "Select",
      player: "Anthony Richardson",
      collectorNumber: "47",
      parallel: "Club Level Gold",
      serialMax: 10,
      autograph: false,
      relic: false,
      displayName: "2023 Select Anthony Richardson #47 Club Level Gold /10",
    },
    intendedAskBandUsd: { low: 15, high: 40 },
    messFlags: ["numbered", "club-level", "gold", "rookie"],
  },
  {
    slot: 21,
    category: "sports",
    fileStem: "2019_mosaic_ja_morant_219_pink_camo_front",
    expected: {
      year: 2019,
      brand: "Mosaic",
      player: "Ja Morant",
      collectorNumber: "219",
      parallel: "Pink Camo",
      serialMax: null,
      autograph: false,
      relic: false,
      displayName: "2019 Mosaic Ja Morant #219 Pink Camo",
    },
    intendedAskBandUsd: { low: 12, high: 32 },
    messFlags: ["rookie", "parallel"],
  },
  {
    slot: 22,
    category: "sports",
    fileStem: "2022_prizm_paolo_banchero_249_fast_break_front",
    expected: {
      year: 2022,
      brand: "Prizm",
      player: "Paolo Banchero",
      collectorNumber: "249",
      parallel: "Fast Break",
      serialMax: null,
      autograph: false,
      relic: false,
      displayName: "2022 Prizm Paolo Banchero #249 Fast Break",
    },
    intendedAskBandUsd: { low: 8, high: 22 },
    messFlags: ["rookie", "parallel"],
  },
  {
    slot: 23,
    category: "sports",
    fileStem: "2021_prizm_cade_cunningham_282_silver_front",
    expected: {
      year: 2021,
      brand: "Prizm",
      player: "Cade Cunningham",
      collectorNumber: "282",
      parallel: "Silver",
      serialMax: null,
      autograph: false,
      relic: false,
      displayName: "2021 Prizm Cade Cunningham #282 Silver",
    },
    intendedAskBandUsd: { low: 8, high: 20 },
    messFlags: ["rookie", "parallel"],
  },
  {
    slot: 24,
    category: "sports",
    fileStem: "2023_bowman_chrome_wyatt_langford_cpa_wl_auto_front",
    expected: {
      year: 2023,
      brand: "Bowman",
      player: "Wyatt Langford",
      collectorNumber: "cpa-wl",
      parallel: null,
      serialMax: null,
      autograph: true,
      relic: false,
      displayName: "2023 Bowman Chrome Wyatt Langford CPA-WL Auto",
    },
    intendedAskBandUsd: { low: 18, high: 45 },
    messFlags: ["auto", "alpha-number"],
  },
  {
    slot: 25,
    category: "sports",
    fileStem: "2020_select_lamelo_ball_63_courtside_red_white_blue_front",
    expected: {
      year: 2020,
      brand: "Select",
      player: "Lamelo Ball",
      collectorNumber: "63",
      parallel: "Courtside Red White Blue",
      serialMax: null,
      autograph: false,
      relic: false,
      displayName: "2020 Select Lamelo Ball #63 Courtside Red White Blue",
    },
    intendedAskBandUsd: { low: 15, high: 40 },
    messFlags: ["insert-level", "parallel", "rookie"],
  },
];

export const BATCH_001_SPORTS_ROSTER: BatchRosterItem[] = RAW.map((row) =>
  BatchRosterItemSchema.parse(row),
);

export function rosterByStem(stem: string): BatchRosterItem | undefined {
  return BATCH_001_SPORTS_ROSTER.find((r) => r.fileStem === stem);
}

export function rosterBySlot(slot: number): BatchRosterItem | undefined {
  return BATCH_001_SPORTS_ROSTER.find((r) => r.slot === slot);
}
