/**
 * Seed rule set sports-headline@0.1.0 (operator-approved 2026-09-27; every
 * number is a starting guess · unverified). Migration 20261001_01 embeds this
 * exact object as rules_json; a test fails if the two drift. The job reads the
 * database row, not this constant.
 */
import type { ClassifierRuleSet } from "./sports-headline.js";

export const SPORTS_HEADLINE_RULES_SEED: ClassifierRuleSet = {
  schema: "vip_signals_classifier_rules_v1",
  classifier: "sports-headline",
  version: "0.1.0",
  domain: "sports_cards",
  scoring: { hedgeFactor: 0.8, singleSourceNoise: 0.3, rulesConfidence: 0.6 },
  noisePatterns: [
    "\\brank(ing|ings)?\\b",
    "\\brerank",
    "\\bpredict",
    "\\bproject(ing|ions?|ed)\\b",
    "\\bodds\\b",
    "\\bbets?\\b",
    "\\bbetting\\b",
    "\\bfantasy\\b",
    "\\bmock draft\\b",
    "\\bgrad(es|ing)\\b",
    "\\bsleepers\\b",
    "\\bpreviews?\\b",
    "\\brecap\\b",
    "\\btiers\\b",
    "\\bbracketology\\b",
    "\\bbubble watch\\b",
    "\\bpoll\\b",
    "^\\W*follow live\\b",
    "\\bdraft (guide|board)\\b",
    "\\bbest of the rest\\b",
    "\\bbuzz\\b",
    "\\bkey questions\\b",
    "\\bwatch list\\b",
    "\\bbottom 10\\b",
    "\\bbreaking down\\b",
    "\\bplaybook\\b",
    "\\bplayoff picture\\b",
    "\\bknee-jerk\\b",
  ],
  hedgePatterns: [
    "\\bsources?\\b",
    "\\breports?\\b",
    "\\bexpected to\\b",
    "\\blikely\\b",
    "\\bat risk\\b",
    "\\bTBD\\b",
    "\\bplans? to\\b",
    "\\bconsidered\\b",
  ],
  rules: [
    {
      type: "PLAYER_DEATH",
      patterns: ["\\bdies\\b", "\\bdied\\b", "\\bdead at\\b", "\\bpasses away\\b"],
      excludePatterns: [],
    },
    {
      type: "PLAYER_INJURY",
      patterns: [
        "\\binjur(y|ed|ies)\\b",
        "\\binjured list\\b",
        "\\bsprain",
        "\\bconcussion\\b",
        "\\btorn\\b",
        "\\bfracture",
        "\\bsurgery\\b",
        "\\bseason-ending\\b",
        "\\bloses .* for (the )?season\\b",
        "\\bto miss\\b",
        "\\bhospitalized\\b",
      ],
      excludePatterns: ["\\bclears?\\b", "\\bcleared\\b", "\\breturns?\\b", "\\brecovered\\b"],
    },
    {
      type: "DISCIPLINE",
      patterns: [
        "\\bsuspend(ed|s|sion)?\\b",
        "\\bfined\\b",
        "\\barrest(ed)?\\b",
        "\\bindict",
        "\\bbanned\\b",
        "\\bconduct detrimental\\b",
        "\\bcharged\\b",
      ],
      excludePatterns: [],
    },
    {
      type: "RETIREMENT",
      patterns: ["\\bretir(e|es|ed|ing|ement)\\b", "\\bhangs? up\\b", "\\bcalls? it a career\\b"],
      excludePatterns: [],
    },
    {
      type: "HOF_ANNOUNCEMENT",
      patterns: ["\\bHall of Fame (class|inductee|induction|ballot)\\b", "\\binducted\\b", "\\belected to\\b.*\\bHall\\b"],
      excludePatterns: [],
    },
    {
      type: "MILESTONE",
      patterns: [
        "\\b40[- /]?HR[- /]40[- /]?SB\\b",
        "\\bjoins?\\b.*\\bclub\\b",
        "\\bbecomes \\d+(st|nd|rd|th)\\b",
        "\\ball-time\\b",
        "\\bbreaks? .*record\\b",
      ],
      excludePatterns: [],
    },
    {
      type: "TRANSACTION",
      patterns: [
        "\\btraded?\\b",
        "\\bre-signs?\\b",
        "\\bsigns?\\b",
        "\\bdeal worth\\b",
        "\\b\\d+-year deal\\b",
        "\\b(gets|inks?|lands?) \\$[\\d.]+M deal\\b",
        "\\bextension\\b",
        "\\bwaived\\b",
        "\\breleased\\b",
        "\\bacquires?\\b",
      ],
      excludePatterns: [],
    },
    {
      type: "AWARD_RACE",
      patterns: ["\\bMVP\\b", "\\bCy Young\\b", "\\bHeisman\\b", "\\bCalder\\b", "\\bRookie of the Year\\b", "\\bbatting title\\b"],
      excludePatterns: [],
    },
  ],
  injurySeverity: {
    season: ["\\bfor (the )?season\\b", "\\bseason-ending\\b", "\\brest of the season\\b", "\\bfor the year\\b"],
    weeks: [
      "\\bIL\\b",
      "\\binjured list\\b",
      "\\bweek[- ]to[- ]week\\b",
      "\\bextended time\\b",
      "\\bweeks\\b",
      "\\buntil\\b",
      "\\bmiss(ing)? (the )?start\\b",
    ],
    day: ["\\bday[- ]to[- ]day\\b", "\\bleaves game\\b", "\\bleft (the |thursday's |\\w+'s )?game\\b", "\\bquestionable\\b"],
  },
  types: {
    PLAYER_INJURY: { direction: "down", impact: { unknown: 0.15, day: 0.15, weeks: 0.3, season: 0.5 } },
    PLAYER_DEATH: { direction: "up", impact: { unknown: 0.6 } },
    MILESTONE: { direction: "up", impact: { unknown: 0.4 } },
    TRANSACTION: { direction: "mixed", impact: { unknown: 0.3 } },
    AWARD_RACE: { direction: "up", impact: { unknown: 0.35 } },
    DISCIPLINE: { direction: "down", impact: { unknown: 0.35 } },
    RETIREMENT: { direction: "mixed", impact: { unknown: 0.3 } },
    HOF_ANNOUNCEMENT: { direction: "up", impact: { unknown: 0.5 } },
  },
  notes:
    "Seed 0.1.0 · unverified. Impacts, hedge factor, single-source noise and rules confidence are starting guesses (operator-approved 2026-09-27), not measurements. Injury with unknown severity takes the smallest injury impact. Replace with a new version calibrated from resolved predictions.",
};
