-- News-only source registry. Not vault_market.data_source.
-- Seed estimates are unverified. Adapters off. Phase 2 off.
-- No signals_normalized writes. No row may raise a valuation ceiling.

BEGIN;

SET search_path TO vault_core, vault_evidence, public;

CREATE TABLE IF NOT EXISTS vault_core.signals_news_source (
    source_key                     TEXT PRIMARY KEY,
    display_name                   TEXT NOT NULL,
    tier                           TEXT NOT NULL
                                   CHECK (tier IN ('machine', 'newsletter')),
    access_method                  TEXT NOT NULL
                                   CHECK (access_method IN (
                                     'rest_api', 'rss', 'rss_or_scrape_check',
                                     'published_file_check', 'gmail_label_poll'
                                   )),
    endpoint                       TEXT,
    auth                           TEXT NOT NULL DEFAULT 'none',
    auth_env_var                   TEXT,
    verify_before_first_run        BOOLEAN NOT NULL DEFAULT true,
    adapter_enabled                BOOLEAN NOT NULL DEFAULT false,
    is_active                      BOOLEAN NOT NULL DEFAULT false,
    blocked_reason                 TEXT,
    cadence                        TEXT,
    latency_notes                  TEXT,
    category_coverage              TEXT[] NOT NULL DEFAULT '{}',
    seed_evidence_class            TEXT NOT NULL,
    seed_confidence_ceiling        NUMERIC(4,3) NOT NULL
                                   CHECK (seed_confidence_ceiling >= 0 AND seed_confidence_ceiling <= 1),
    authority_seed                 NUMERIC(4,3)
                                   CHECK (authority_seed IS NULL OR (authority_seed >= 0 AND authority_seed <= 1)),
    historical_accuracy_seed       NUMERIC(4,3)
                                   CHECK (historical_accuracy_seed IS NULL OR (historical_accuracy_seed >= 0 AND historical_accuracy_seed <= 1)),
    redistribution_allowed         BOOLEAN NOT NULL DEFAULT false
                                   CHECK (redistribution_allowed = false),
    may_raise_valuation_ceiling    BOOLEAN NOT NULL DEFAULT false
                                   CHECK (may_raise_valuation_ceiling = false),
    terms                          TEXT NOT NULL,
    dedup_keys                     TEXT[] NOT NULL DEFAULT '{}',
    iqvault_only                   BOOLEAN NOT NULL DEFAULT false,
    request_notes                  JSONB NOT NULL DEFAULT '[]'::jsonb,
    known_failure_modes            JSONB NOT NULL DEFAULT '[]'::jsonb,
    why_it_earns_a_slot            TEXT,
    provider_ids                   JSONB NOT NULL DEFAULT '{}'::jsonb,
    prov_source                    TEXT NOT NULL,
    prov_method                    vault_evidence.provenance_method NOT NULL DEFAULT 'inferred',
    prov_rule_version              TEXT NOT NULL,
    prov_confidence                NUMERIC(4,3) NOT NULL
                                   CHECK (prov_confidence >= 0 AND prov_confidence <= 1),
    prov_verification              vault_evidence.verification_status NOT NULL DEFAULT 'unverified',
    prov_notes                     TEXT,
    created_at                     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS signals_news_source_tier_idx
  ON vault_core.signals_news_source (tier, adapter_enabled, is_active);

COMMENT ON TABLE vault_core.signals_news_source IS
  'News / narrative sources only. Not a price authority. Not vault_market.data_source. authority_seed is a seed estimate · unverified. adapter_enabled stays false until an operator flips it after verify_before_first_run. Phase 2 off.';

INSERT INTO vault_core.signals_news_source (
  source_key, display_name, tier, access_method, endpoint, auth, auth_env_var,
  verify_before_first_run, adapter_enabled, is_active, blocked_reason,
  cadence, latency_notes, category_coverage, seed_evidence_class,
  seed_confidence_ceiling, authority_seed, historical_accuracy_seed,
  terms, dedup_keys, iqvault_only, why_it_earns_a_slot,
  prov_source, prov_rule_version, prov_confidence, prov_notes
) VALUES
  ('gdelt_doc_v2', 'GDELT DOC 2.0', 'machine', 'rest_api',
   'https://api.gdeltproject.org/api/v2/doc/doc', 'none', NULL,
   false, false, false, NULL, 'hourly', '~15 minutes behind publication',
   ARRAY['macro','pokemon','sports_cards','comics','lego','collectibles_general'],
   'third_party_narrative', 0.60, 0.70, NULL,
   'GDELT open-platform terms. Store metadata and links, never full article bodies.',
   ARRAY['url_canonical','title_normalized+domain'], false,
   'Highest-volume free input; native attention-volume series.',
   'signals_news_seed', 'signals-news-source@0.1.0', 0.600,
   'authority_seed is a seed estimate · unverified. Adapter off. Phase 2 off.'),
  ('fred', 'FRED (St. Louis Fed)', 'machine', 'rest_api',
   'https://api.stlouisfed.org/fred/series/observations', 'api_key_free', 'FRED_API_KEY',
   false, false, false, NULL, 'daily', 'monthly series lag 2-6 weeks',
   ARRAY['macro','metals'],
   'official_statistic', 0.95, 0.95, NULL,
   'Public domain US government data. Attribution required. No Fed endorsement implied. Not a collectibles price authority.',
   ARRAY['series_id+observation_date+realtime_start'], false,
   'Discretionary-spend macro context. Revisions must append, not overwrite.',
   'signals_news_seed', 'signals-news-source@0.1.0', 0.750,
   'authority_seed is a seed estimate · unverified. Adapter off. Phase 2 off.'),
  ('sec_edgar_fts', 'SEC EDGAR Full-Text Search', 'machine', 'rest_api',
   'https://efts.sec.gov/LATEST/search-index', 'none', NULL,
   false, false, false, NULL, 'daily', 'same day as filing acceptance',
   ARRAY['macro','sports_cards','pokemon','collectibles_general'],
   'primary_disclosure', 0.90, 0.95, NULL,
   'Public domain. Fair-access policy. Descriptive User-Agent with contact email required.',
   ARRAY['accession_number+matched_document'], false,
   'Primary disclosure, not reported narrative.',
   'signals_news_seed', 'signals-news-source@0.1.0', 0.750,
   'authority_seed is a seed estimate · unverified. Adapter off. Phase 2 off.'),
  ('comicsbeat_rss', 'The Beat (comics)', 'machine', 'rss',
   'https://www.comicsbeat.com/feed/', 'none', NULL,
   false, false, false, NULL, '4x daily', 'minutes',
   ARRAY['comics'],
   'trade_press', 0.65, 0.75, NULL,
   'Standard RSS. Title, link, timestamp, summary only. Not a comics price authority.',
   ARRAY['guid','url_canonical'], false,
   'Comics trade-press news. Never let a Beat post move a valuation.',
   'signals_news_seed', 'signals-news-source@0.1.0', 0.650,
   'authority_seed is a seed estimate · unverified. Adapter off. Phase 2 off.'),
  ('polygon_rss', 'Polygon', 'machine', 'rss',
   'https://www.polygon.com/rss/index.xml', 'none', NULL,
   true, false, false, 'verify_before_first_run',
   '4x daily', 'minutes',
   ARRAY['pokemon','lego','collectibles_general','culture'],
   'trade_press', 0.55, 0.60, NULL,
   'Standard RSS. Metadata and links only.',
   ARRAY['guid','url_canonical'], false,
   'Cultural-relevance input. Needs topic filtering.',
   'signals_news_seed', 'signals-news-source@0.1.0', 0.550,
   'authority_seed is a seed estimate · unverified. Endpoint not confirmed live. Adapter off. Phase 2 off.'),
  ('espn_rss', 'ESPN (sports news)', 'machine', 'rss',
   NULL, 'none', NULL,
   true, false, false, 'discover per-sport feeds; commercial-use terms unresolved',
   'hourly during season', 'minutes',
   ARRAY['sports_cards'],
   'trade_press', 0.55, 0.65, NULL,
   'ESPN RSS personal/non-commercial. IQVault-only until VaultOS terms are resolved.',
   ARRAY['guid','url_canonical'], true,
   'Player news vs sports-card comps is a backtestable hypothesis. Not a price feed.',
   'signals_news_seed', 'signals-news-source@0.1.0', 0.550,
   'authority_seed is a seed estimate · unverified. Adapter off. Phase 2 off.'),
  ('wizards_dailymtg', 'Daily MTG (Wizards of the Coast)', 'machine', 'rss_or_scrape_check',
   NULL, 'none', NULL,
   true, false, false, 'no published feed confirmed; do not scrape',
   'daily', 'hours',
   ARRAY['mtg'],
   'publisher_primary', 0.85, 0.90, NULL,
   'Publisher site. If no RSS is published, defer — do not scrape.',
   ARRAY['guid','url_canonical'], false,
   'First-party reprint / schedule / banlist announcements.',
   'signals_news_seed', 'signals-news-source@0.1.0', 0.750,
   'authority_seed is a seed estimate · unverified. Adapter off. Phase 2 off.'),
  ('lbma_precious_metals', 'LBMA Precious Metal Prices', 'machine', 'published_file_check',
   'https://www.lbma.org.uk/prices-and-data/lbma-precious-metal-prices', 'none', NULL,
   true, false, false, 'licensing unresolved; prefer FRED metals series',
   'daily', 'daily fix',
   ARRAY['metals'],
   'benchmark_price', 0.90, 0.95, NULL,
   'CAUTION: commercial license. Confirm before any VaultOS use. Prefer FRED if equivalent.',
   ARRAY['metal+fix_date+fix_session'], false,
   'Metals benchmark only if licensing clears. Not a collectibles price authority.',
   'signals_news_seed', 'signals-news-source@0.1.0', 0.600,
   'authority_seed is a seed estimate · unverified. Adapter off. Phase 2 off.'),
  ('stratechery', 'Stratechery', 'newsletter', 'gmail_label_poll',
   NULL, 'subscription', NULL,
   true, false, false, 'gmail inbound unconfirmed as of 2026-09-20',
   '4x weekly', NULL,
   ARRAY['macro','tech_business'],
   'expert_analysis', 0.70, 0.85, NULL,
   'Licensed by subscription. Poll a Gmail label. Never store recipient address.',
   ARRAY['message_id'], false,
   'Platform / marketplace dynamics. Blocked until Gmail receives mail.',
   'signals_news_seed', 'signals-news-source@0.1.0', 0.700,
   'authority_seed is a seed estimate · unverified. Adapter off. Phase 2 off.'),
  ('sherwood_news', 'Sherwood News', 'newsletter', 'gmail_label_poll',
   NULL, 'subscription', NULL,
   true, false, false, 'gmail inbound unconfirmed as of 2026-09-20',
   'daily', NULL,
   ARRAY['macro','markets'],
   'trade_press', 0.60, 0.65, NULL,
   'Licensed by subscription. Poll a Gmail label. Never store recipient address.',
   ARRAY['message_id'], false, NULL,
   'signals_news_seed', 'signals-news-source@0.1.0', 0.600,
   'authority_seed is a seed estimate · unverified. Adapter off. Phase 2 off.'),
  ('daily_upside', 'The Daily Upside', 'newsletter', 'gmail_label_poll',
   NULL, 'subscription', NULL,
   true, false, false, 'gmail inbound unconfirmed as of 2026-09-20',
   'daily', NULL,
   ARRAY['macro','markets'],
   'trade_press', 0.60, 0.65, NULL,
   'Licensed by subscription. Poll a Gmail label. Never store recipient address.',
   ARRAY['message_id'], false, NULL,
   'signals_news_seed', 'signals-news-source@0.1.0', 0.600,
   'authority_seed is a seed estimate · unverified. Adapter off. Phase 2 off.'),
  ('exec_sum', 'Exec Sum', 'newsletter', 'gmail_label_poll',
   NULL, 'subscription', NULL,
   true, false, false, 'gmail inbound unconfirmed as of 2026-09-20',
   'daily', NULL,
   ARRAY['macro','markets'],
   'aggregator', 0.50, 0.50, NULL,
   'Licensed by subscription. Dedup test fixture against GDELT.',
   ARRAY['message_id'], false,
   'Aggregator. If dedup misses these, the layer is not working.',
   'signals_news_seed', 'signals-news-source@0.1.0', 0.500,
   'authority_seed is a seed estimate · unverified. Adapter off. Phase 2 off.'),
  ('the_ai_report', 'The AI Report', 'newsletter', 'gmail_label_poll',
   NULL, 'subscription', NULL,
   true, false, false, 'gmail inbound unconfirmed as of 2026-09-20',
   'daily', NULL,
   ARRAY['ai_ml'],
   'trade_press', 0.50, 0.55, NULL,
   'Keep in its own category. Never join to an asset impact.',
   ARRAY['message_id'], false,
   'Not a collectibles signal.',
   'signals_news_seed', 'signals-news-source@0.1.0', 0.500,
   'authority_seed is a seed estimate · unverified. Adapter off. Phase 2 off.'),
  ('milk_road', 'Milk Road', 'newsletter', 'gmail_label_poll',
   NULL, 'subscription', NULL,
   true, false, false, 'gmail inbound unconfirmed as of 2026-09-20',
   'daily', NULL,
   ARRAY['crypto','alt_assets'],
   'trade_press', 0.40, 0.40, NULL,
   'Risk-appetite proxy only. Never evidence for a specific asset.',
   ARRAY['message_id'], false,
   'Lowest authority in the set.',
   'signals_news_seed', 'signals-news-source@0.1.0', 0.400,
   'authority_seed is a seed estimate · unverified. Adapter off. Phase 2 off.')
ON CONFLICT (source_key) DO NOTHING;

COMMIT;
